version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: task-tracker-db
    environment:
      POSTGRES_DB: task_tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"  # 5433 на компьютере → 5432 в контейнере
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d task_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: